// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ifxUz96GhYoFEKMwzvUAFDAjsFyB9JQ',
    appId: '1:954304825558:web:b9930fb904d841f24fe177',
    messagingSenderId: '954304825558',
    projectId: 'groceryshop-d6c48',
    authDomain: 'groceryshop-d6c48.firebaseapp.com',
    storageBucket: 'groceryshop-d6c48.firebasestorage.app',
    measurementId: 'G-H2D5S46CJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSx-shE8uQAnTc3TGuWl6IC1palYHJSyU',
    appId: '1:954304825558:android:416ee56d8eb111c04fe177',
    messagingSenderId: '954304825558',
    projectId: 'groceryshop-d6c48',
    storageBucket: 'groceryshop-d6c48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGR0ynKofJ2-teGLXHjzXPdtCreod3cM4',
    appId: '1:954304825558:ios:0ec6ed7b728f085d4fe177',
    messagingSenderId: '954304825558',
    projectId: 'groceryshop-d6c48',
    storageBucket: 'groceryshop-d6c48.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGR0ynKofJ2-teGLXHjzXPdtCreod3cM4',
    appId: '1:954304825558:ios:0ec6ed7b728f085d4fe177',
    messagingSenderId: '954304825558',
    projectId: 'groceryshop-d6c48',
    storageBucket: 'groceryshop-d6c48.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ifxUz96GhYoFEKMwzvUAFDAjsFyB9JQ',
    appId: '1:954304825558:web:e141453e52ce6a404fe177',
    messagingSenderId: '954304825558',
    projectId: 'groceryshop-d6c48',
    authDomain: 'groceryshop-d6c48.firebaseapp.com',
    storageBucket: 'groceryshop-d6c48.firebasestorage.app',
    measurementId: 'G-FS8X4KMWEB',
  );

}